### PR TITLE
#14 docs: create how to use resource (add poetry usage)

### PR DESCRIPTION
**Pull request by gatheluck**
## Issue URL

https://github.com/cvpaperchallenge/Ascender/issues/14

## Change overview

- Add [slidev](https://sli.dev/) to create how to use resource.
- Add poetry usage. 

## How to test

prerequisite: node

```
$ cd slidev
$ npm install
$ npm run dev
# You can see the resource from  http://localhost:3030/
```

## Note for reviewers

- How to use resource is not completed yet. I'm going to host SPA created by slidev by using  github page feature.

### CODE REVIEW

**Review by ueda0319 — COMMENTED** [review]
The current code outputs the following error at build time.　Do you have any idea?

```
$ npm run dev

> dev
> slidev --open

~/Projects/Ascender/slidev/node_modules/@iconify/utils/lib/loader/node-loader.cjs:31
  const iconSet = await loader_fs.loadCollectionFromFS(collection, options?.autoInstall);
                                                                           ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (~/Projects/Ascender/slidev/node_modules/unplugin-icons/dist/chunk-KPZ5JDNI.js:57:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by gatheluck** [comment]
@ueda0319  Thank you! I'm not sure this is a reason but firstly could you teach me your node version? Slidev requires `Node.js>=14`.

**Comment by ueda0319** [comment]
The `npm install` was terminating without error, but the node update solved the problem.
Below are the versions of success and failure, just in case.
Failure: `node=v12.22.12, npm=8.10.0`
Success: `node=v16.15.0, npm=8.5.5`

This is just a suggestion, but it would be nice to have the version information of node and npm.

**Review by ueda0319 — APPROVED** [review]
Thank you for your suggestion.
I have confirmed that slidev works, LGTM!
It will be a good document to understand when we have more information to link!

**Pull request merged**
