### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by copipe**
`dokcer` -> `docker`

### CODE REVIEW

**Comment by gatheluck** [comment]
@copipe Thank you for pointing this out and fix it! Could you change the target branch from `master` to `develop`? We have branch protection rule, and only `develop` branch is able to merge into `master`. Sorry for bothering you.

**Comment by copipe** [comment]
@gatheluck 
Thank you for your reply.
I changed the merge destination from master to develop.

**Review by gatheluck — APPROVED** [review]
Thank you for your update, LGTM! Please feel free to merge this PR into `develop` branch. This change will be reflected to `master` branch at next release. @copipe

**Comment by copipe** [comment]
@gatheluck 
Thank you for your review!
But I probably don't have permission to merge, so I can't see the merge button. So I would like you to merge this PR into develop branch.

**Comment by gatheluck** [comment]
Thank you! OK, I merge this branch!

**Pull request merged**
